// Generated by https://quicktype.io

export interface ProductInCart {
	product: Product;
	quantity: number;
}

export interface Product {
	id: string;
	slug: string;
	name: string;
	isTop: boolean;
	image: CategoryImage;
	category: string;
	categoryImage: CategoryImage;
	new: boolean;
	price: number;
	description: string;
	features: string;
	includes: Include[];
	gallery: Gallery;
	others: Other[];
}

export interface CategoryImage {
	mobile: string;
	tablet: string;
	desktop: string;
}

export interface Gallery {
	first: CategoryImage;
	second: CategoryImage;
	third: CategoryImage;
}

export interface Include {
	quantity: number;
	item: string;
}

export interface Other {
	slug: string;
	name: string;
	image: CategoryImage;
}

export type CheckoutForm = {
	billingDetails: BillingDetails;
	shippingInfo: ShippingInfo;
	paymentDetails: PaymentDetails;
};

export type BillingDetails = {
	name: string;
	emailAddress: string;
	phoneNumber: string;
};
export type ShippingInfo = {
	yourAddress: string;
	zipCode: string;
	city: string;
	country: string;
};

export type PaymentDetails = {
	paymentMethod: PaymentMethod.CASH | PaymentMethod.EMONEY;
} & (
	| {
			paymentMethod: PaymentMethod.CASH;
			emoneyNumber?: never;
			emoneyPin?: never;
	  }
	| {
			paymentMethod: PaymentMethod.EMONEY;
			emoneyNumber: string;
			emoneyPin: string;
	  }
);

export enum PaymentMethod {
	EMONEY = 'e-Money',
	CASH = 'Cash on Delivery',
}
